CUDA_VISIBLE_DEVICES=2 python3 test_3d.py \
    --dataset_mode london_pc \
    --dataroot datasets/london_half_pc \
    --phase test300 \
    --checkpoints_dir checkpoints/sate_pc_scnrn_coord_glb \
    --num_frames 15 \
    --input_nc 3 \
    --nz 16 \
    --ngf 64 \
    --netG sparseconvnetmultinoise \
    --scn_ratio 32 \
    --netE resnet_256_multi \
    --rn_ratio 0.1 \
    --local_encoder \
    --save_img \
    --epoch 32000 \
    --n_samples 5 \
    --results_dir results_sate_pc_scnrn_coord_glb
